{% set name = "pytest-reverse" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f943e5b9d253267569fd7ad237afc56b3e98ce9f6d2f6f3bb487b8c759e214fe

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - pytest

test:
  commands:
    - py.test --traceconfig | grep pytest-reverse-{{ version }}

about:
  home: https://github.com/adamchainz/pytest-reverse
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pytest plugin to reverse test order.
  # The remaining entries in this section are optional, but recommended.
  description: |
    Pytest will automatically find the plugin and use it when you run pytest. 
    You can reverse test order by passing the --reverse flag.
  doc_url: https://github.com/adamchainz/pytest-reverse
  dev_url: https://github.com/adamchainz/pytest-reverse

extra:
  recipe-maintainers:
    - ReimarBauer
