{% set name = "pytest-reverse" %}

{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a3b756f13bfc5b9aa39bfc57d2d5e03ec62f7fdfed2c04cad664c283d63ce94a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - pytest

test:
  commands:
    - py.test --traceconfig | grep pytest-reverse-{{ version }}

about:
  home: https://github.com/adamchainz/pytest-reverse
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pytest plugin to reverse test order.
  # The remaining entries in this section are optional, but recommended.
  description: |
    Pytest will automatically find the plugin and use it when you run pytest. 
    You can reverse test order by passing the --reverse flag.
  doc_url: https://github.com/adamchainz/pytest-reverse
  dev_url: https://github.com/adamchainz/pytest-reverse

extra:
  recipe-maintainers:
    - ReimarBauer
