{% set name = "pytest-reverse" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9f2a3b163378922dd332ed056a58af4cfd1ccc8ad4a76606f43ed43cfff2140b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - pytest

test:
  commands:
    - py.test --traceconfig | grep pytest-reverse-{{ version }}

about:
  home: https://github.com/adamchainz/pytest-reverse
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pytest plugin to reverse test order.
  # The remaining entries in this section are optional, but recommended.
  description: |
    Pytest will automatically find the plugin and use it when you run pytest. 
    You can reverse test order by passing the --reverse flag.
  doc_url: https://github.com/adamchainz/pytest-reverse
  dev_url: https://github.com/adamchainz/pytest-reverse

extra:
  recipe-maintainers:
    - ReimarBauer
